import type { CSSProperties } from "react";

export const navStyles: Record<string, CSSProperties> = {
  wrapper: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    display: "flex",
    justifyContent: "center",
    padding: "20px 24px 0",
    pointerEvents: "none",
    zIndex: 50,
  },
  navbar: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    borderRadius: "9999px",
    padding: "8px 12px",
    minWidth: "700px",
    transition:
      "opacity 0.6s ease, transform 0.6s cubic-bezier(0.34,1.56,0.64,1)",
    pointerEvents: "auto",
  },
  linkList: {
    display: "flex",
    alignItems: "center",
    gap: "2px",
    listStyle: "none",
    margin: "0 8px",
    padding: 0,
    flex: 1,
    justifyContent: "center",
  },
  linkItem: {
    margin: 0,
    padding: 0,
  },
  linkBtn: {
    position: "relative",
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "12px 22px",
    borderRadius: "9999px",
    fontSize: "16px",
    letterSpacing: "0.01em",
    color: "rgba(255,255,255,0.75)",
    transition: "color 0.2s ease",
    whiteSpace: "nowrap",
    fontFamily: "inherit",
  },
  userBtn: {
    flexShrink: 0,
    width: "54px",
    height: "54px",
    borderRadius: "50%",
    background: "rgba(255,255,255,0.94)",
    border: "1px solid rgba(255,255,255,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    boxShadow: "0 2px 12px rgba(255,255,255,0.12)",
    transition: "transform 0.15s, box-shadow 0.2s",
  },
};
